ALTER TABLE sync.inbox_operations
    ADD COLUMN request_hash VARCHAR(64)
        CHECK (request_hash IS NULL OR request_hash ~ '^[a-f0-9]{64}$');

ALTER TABLE sync.outbox_events
    ADD COLUMN global_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN branch_id UUID REFERENCES organization.branches(branch_id),
    ADD COLUMN warehouse_id UUID REFERENCES organization.warehouses(warehouse_id);

ALTER TABLE sync.outbox_events
    ADD CONSTRAINT uq_outbox_global_sequence UNIQUE (global_sequence);

ALTER TABLE sync.device_checkpoints
    ADD COLUMN last_acknowledged_outbox_sequence BIGINT NOT NULL DEFAULT 0
        CHECK (last_acknowledged_outbox_sequence >= 0);

CREATE INDEX idx_outbox_sequence_scope
    ON sync.outbox_events (global_sequence, branch_id);

CREATE INDEX idx_conflicts_unresolved
    ON sync.conflicts (created_at DESC)
    WHERE resolved_at IS NULL;

CREATE OR REPLACE FUNCTION sync.publish_business_event_to_outbox()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    resolved_branch_id UUID;
    resolved_warehouse_id UUID;
BEGIN
    IF NEW.aggregate_type NOT IN (
        'PRODUCT',
        'PRODUCT_PRESENTATION',
        'CUSTOMER',
        'CART',
        'INVENTORY_COUNT',
        'STOCK_MOVEMENT',
        'INVENTORY_RECEIPT'
    ) THEN
        RETURN NEW;
    END IF;

    IF NEW.aggregate_type = 'CART' THEN
        SELECT branch_id
          INTO resolved_branch_id
          FROM sales.carts
         WHERE cart_id = NEW.aggregate_id;
    ELSIF NEW.aggregate_type = 'INVENTORY_COUNT' THEN
        SELECT warehouse.branch_id, count_record.warehouse_id
          INTO resolved_branch_id, resolved_warehouse_id
          FROM inventory.inventory_counts count_record
          JOIN organization.warehouses warehouse
            ON warehouse.warehouse_id = count_record.warehouse_id
         WHERE count_record.inventory_count_id = NEW.aggregate_id;
    ELSIF NEW.aggregate_type = 'STOCK_MOVEMENT' THEN
        SELECT warehouse.branch_id, movement.warehouse_id
          INTO resolved_branch_id, resolved_warehouse_id
          FROM inventory.stock_movements movement
          JOIN organization.warehouses warehouse
            ON warehouse.warehouse_id = movement.warehouse_id
         WHERE movement.stock_movement_id = NEW.aggregate_id;
    ELSIF NEW.aggregate_type = 'INVENTORY_RECEIPT' THEN
        SELECT warehouse.branch_id, movement.warehouse_id
          INTO resolved_branch_id, resolved_warehouse_id
          FROM inventory.stock_movements movement
          JOIN organization.warehouses warehouse
            ON warehouse.warehouse_id = movement.warehouse_id
         WHERE movement.stock_movement_id = NEW.aggregate_id;
    END IF;

    INSERT INTO sync.outbox_events (
        aggregate_type,
        aggregate_id,
        event_type,
        payload,
        correlation_id,
        branch_id,
        warehouse_id
    ) VALUES (
        NEW.aggregate_type,
        NEW.aggregate_id,
        NEW.event_type,
        jsonb_build_object(
            'aggregateType', NEW.aggregate_type,
            'aggregateId', NEW.aggregate_id,
            'eventType', NEW.event_type,
            'state', COALESCE(NEW.after_state, '{}'::jsonb),
            'occurredAt', NEW.created_at
        ),
        NEW.correlation_id,
        resolved_branch_id,
        resolved_warehouse_id
    );

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_business_event_sync_outbox
AFTER INSERT ON audit.business_events
FOR EACH ROW
EXECUTE FUNCTION sync.publish_business_event_to_outbox();

INSERT INTO iam.permissions (code, name, module, description)
VALUES
 ('SYNC_INBOX_WRITE', 'Enviar operaciones offline', 'SYNC', 'Permite enviar operaciones offline idempotentes'),
 ('SYNC_OUTBOX_READ', 'Consultar eventos de sincronizacion', 'SYNC', 'Permite descargar eventos de sincronizacion por dispositivo'),
 ('SYNC_CHECKPOINT_READ', 'Consultar checkpoint de dispositivo', 'SYNC', 'Permite consultar el progreso de sincronizacion'),
 ('SYNC_CHECKPOINT_ACK', 'Confirmar checkpoint de dispositivo', 'SYNC', 'Permite confirmar eventos procesados por el dispositivo'),
 ('SYNC_CONFLICT_READ', 'Consultar conflictos de sincronizacion', 'SYNC', 'Permite consultar conflictos offline'),
 ('SYNC_CONFLICT_RESOLVE', 'Resolver conflictos de sincronizacion', 'SYNC', 'Permite resolver conflictos offline')
ON CONFLICT (code) DO NOTHING;

INSERT INTO iam.role_permissions (role_id, permission_id)
SELECT role.role_id, permission.permission_id
FROM iam.roles role
CROSS JOIN iam.permissions permission
WHERE role.code = 'SYSTEM_ADMIN'
  AND permission.code IN (
    'SYNC_INBOX_WRITE',
    'SYNC_OUTBOX_READ',
    'SYNC_CHECKPOINT_READ',
    'SYNC_CHECKPOINT_ACK',
    'SYNC_CONFLICT_READ',
    'SYNC_CONFLICT_RESOLVE'
  )
ON CONFLICT (role_id, permission_id) DO NOTHING;
